### PR TITLE
docs(extending-workflow): add a list of community projects around workflow

### LINKED ISSUE #577: add a workflow community projects page
In v1 we had a `contrib` directory that [contained a README](https://github.com/deis/deis/blob/master/contrib/README.md) with all of the v1-related community projects we were aware of. Re-introducing a document providing links of all Workflow-related projects we are aware of would be a welcome addition to the docs.

### PR DESCRIPTION
**Pull request by mboersma**
What other projects should be listed here?

Closes #577. ping @olalonde

### CODE REVIEW

**Comment by bacongobbler** [comment]
[jumbojett/deis-ui](https://github.com/jumbojett/deis-ui) is another project that can work on v2, but is currently broken.

[olalonde/deisdash](https://github.com/olalonde/deisdash) is another project.

**Comment by olalonde** [comment]
+1 for https://github.com/olalonde/deisdash :) There's also

- https://github.com/jumbojett/deis-ui though I'm not sure if still maintained. 
- https://github.com/olalonde/deis-node (JavaScript API client, not updated in a while)

A quick search on GitHub turned up:

- https://github.com/Ragnarson/deis-cleanup (deis v1)
- https://github.com/rimusz/deis-workflow-aws
- https://github.com/rimusz/deis-workflow-gke

**Comment by bacongobbler** [comment]
Right, I guess there's also https://github.com/TheNewNormal/kube-solo-osx that includes documentation on getting Workflow installed on kube-solo

**Comment by mboersma** [comment]
Updated with all the community projects mentioned above.

**Comment by ultimateboy** [comment]
A few more:

https://github.com/thomas0087/deis-workflow-ruby
https://github.com/emartech/heroku-to-deis
https://github.com/Rafflecopter/deis-global-config-plugin

**Comment by mboersma** [comment]
Updated with three more links and a disclaimer suggested by @ultimateboy.

**Pull request merged**
