### PR TITLE
fix(_tests,Makefile): remove integration tests

### PR DESCRIPTION
**Pull request by arschles**
They are now in https://github.com/deis/workflow-e2e

Fixes https://github.com/deis/workflow-e2e/issues/6

### CODE REVIEW

**Comment by slack** [comment]
With non-blocking comment to change the Makefile `test-integration` to echo something about checking workflow-e2e...

**Comment by arschles** [comment]
>With non-blocking comment
what's a non-blocking comment?

**Comment by slack** [comment]
Oh, something I made up on the fly!

Just a suggestion to reduce potential confusion for folks expecting `make test-integration` to work... but wouldn't block this PR from acceptance.

**Comment by arschles** [comment]
Ah, got it. Good idea. Just added comment in https://github.com/arschles/workflow/commit/9213b8ecc380845043f4ab1b7f19012ab0ade810, gonna rebase and merge

**Comment by arschles** [comment]
Oops, nvm. Didn't need a rebase, just need to wait for tests. I'm rushing too much...

**Pull request merged**
