### PR TITLE
fix(scheduler): slug url was replacing : with -, which is not accurate

### LINKED ISSUE #269: Slug URL in generated RCs is wrong
There's an error somewhere in here that results in the slug URL set on the rc to be malformed.  It might look like this, for example:

```
http://10.3.0.171:9000/git/home/nimbus-barbecue-git-afb7db0a/push/slug.tgz
```

Despite the fact that the actual URL where the slug can be found is this:

```
http://10.3.0.171:9000/git/home/nimbus-barbecue:git-afb7db0a/push/slug.tgz
```

In case it's tough to spot, the difference is a dash vs a colon separating the image name from the tag.

The result is that the slugrunner gets a 404 when it uses mc to try to fetch the slug.  This sends the pod into a CrashLoopBackOff.

It looks like the issue was recently introduced in here somewhere:

https://github.com/deis/workflow/blob/master/rootfs/scheduler/__init__.py#L605-L627

### PR DESCRIPTION
**Pull request by helgi**
Fixes #269

### CODE REVIEW

**Comment by arschles** [comment]
LGTM, I'll add the label when I get back to computer

**Comment by krancour** [comment]
@helgi was there some defensible reason that replacement was happening in the first place?  I was imagining that there had been.  Just want to make sure we're not breaking some other case now.

**Comment by helgi** [comment]
Outlined it in the ticket but it was part of other work @arschles and I were doing, didn't really crop up since we were using the go rewrite of builder

**Comment by arschles** [comment]
Chiming in late here - what @helgi said is correct. I tested the original (breaking) pull request with a builder that was known not to work at the time (https://github.com/deis/builder/pull/72, now working against `v2-beta` workflow), but not with a known-working builder

**Pull request merged**
