### PR TITLE
docs(*): add upgrade note for gcs/gcr

### PR DESCRIPTION
**Pull request by vdice**
Ref https://github.com/deis/registry-token-refresher/pull/7
Ref https://github.com/deis/workflow/pull/672

### CODE REVIEW

**Comment by bacongobbler** [comment]
The code block doesn't render inside the admonition so it looks a bit awkward when reading it

2017-01-05-120802_3840x1080_scrot

Perhaps we should do away with the admonition here?

**Comment by vdice** [comment]
@bacongobbler good point -- changed; let me know if that's what you had in mind.

**Comment by mboersma** [comment]
I'm ok with it either way, honestly. Here is what it looks like after the latest update:
screen shot 2017-01-05 at 2 14 08 pm

**Comment by bacongobbler** [comment]
Much better :)

**Pull request merged**
