### PR TITLE
feat(tags): implement tags as k8s node selectors

### LINKED ISSUE #168: `deis tag` should add nodeSelector to pod template
I guess that our plan for `deis tag` is to have it create node selectors as documented here: http://kubernetes.io/v1.1/docs/user-guide/node-selection/README.html

### PR DESCRIPTION
**Pull request by helgi**
Implement deis tags as k8s nodeSelector. Uses the /nodes API endpoint to verify if a label already exists or not. Multiple labels compound.

This is the first implementation of labelSelector and fieldSelector on a GET call. It will be ported to most of the GET functions eventually

Depends on #260
Fixes #168

### CODE REVIEW

**Comment by arschles** [comment]
@helgi this lgtm, but I'd like to test it manually first. any specific things I should try here (I'm assuming something around `deis tag`...)?

**Comment by helgi** [comment]
You can try it with `deis tags:set env=prod -a <app>`

For it to work you need a k8s node with `metadata.labels.env=prod`. You can do this by finding your node(s) via `k get nodes` and then editing them.

If you do a tag for a label that doesn't exist it throw a 400 with a message

**Comment by arschles** [comment]
@helgi everything seems to work here, except for setting a tag for a label that doesn't exist, which succeeds from the CLI (it doesn't throw a 400). For example:

```console
ENG000656:example-go aaronschlesinger$ deis tags:set blah=asda -a gotest
Applying tags... done

=== gotest Tags
blah     asda
env      prod
```

**Comment by arschles** [comment]
@helgi just tested again, this time with an updated build of your branch. things look good:

```console
ENG000656:example-go aaronschlesinger$ deis tags:set blah=asdas -a gotest
Applying tags... Error: 
400 Bad Request
detail: These tags do not match labels on kubernetes nodes: blah=asdas, env=prod
```

**Pull request merged**
