### PR TITLE
docs(applications): explain how to add user ssh key

### PR DESCRIPTION
**Pull request by rimusz**

### CODE REVIEW

**Comment by rimusz** [comment]
replacing #295, all recommendations are done

**Comment by rimusz** [comment]
ping @arschles

**Comment by bacongobbler** [comment]
would you mind squashing your two commits into one, please?

**Comment by bacongobbler** [comment]
Now there's 4 commits. ;) The easiest way to squash commits is to use `git rebase -i master` and mark all except the original commit as a `fixup`. This will cause all the commits to merge into the first commit.

**Comment by rimusz** [comment]
OMG what I have done :)

**Comment by rimusz** [comment]
ah, still getting issues there, will close this and will do the new clean one

**Pull request closed without merging**
