### PR TITLE
fix(serializer): JSON is already translated in some cases so pass through

### PR DESCRIPTION
**Pull request by helgi**

### CODE REVIEW

**Comment by helgi** [comment]
Using the CLI would show this problem but tests never caught it. `deis config` and `deis tags`

**Comment by bacongobbler** [comment]
looks like you need to import the json library for tests to pass

**Comment by smothiki** [comment]
I have made a recent change to how we handle cpu units and hitting this issue 
```
 deis limits:set  -m web=200mb
Applying limits... Error: 
400 Bad Request
memory: Value must be valid JSON.
```

**Comment by helgi** [comment]
Relates to #250

**Pull request merged**
