### PR TITLE
ref(Makefile): change component name to controller

### PR DESCRIPTION
**Pull request by bacongobbler**
Images will now get pushed to deisci/controller

refs https://github.com/deis/deis/issues/4952

TODO:

 - [x] create Dockerhub and quay.io repositories for deisci/controller and deis/controller (EDIT: these already existed!)

### CODE REVIEW

**Comment by mboersma** [comment]
The Makefile still references "workflow" in two `kubectl` commands at `make deploy`. Should that change with this PR?

**Comment by helgi** [comment]
Yeah, it will have to, at least needs to be changed in tandem with the charts

**Comment by bacongobbler** [comment]
that workflow won't work any more with https://github.com/deis/charts/pull/148. I'm looking to pull that all out in a follow-up.

**Comment by bacongobbler** [comment]
PR #495 addresses your concerns. :)

**Pull request merged**
