### PR TITLE
docs(styles) sticky footer to avoid overlap with sidebar

### PR DESCRIPTION
**Pull request by flynnduism**
sticky-footer

Layout change to the Docs, moving the footer out of the sidebar; to avoid overlaps like [#231](https://github.com/deis/deis.com/issues/231).

### CODE REVIEW

**Comment by slack** [comment]
Tested locally, looks good.

**Comment by slack** [comment]
I did get a fatty gutter in Chrome, but no biggie.

**Comment by slack** [comment]
2016-09-06 at 17 14

**Comment by slack** [comment]
For the record, the gutter isn't a blocker! 💃

**Comment by ultimateboy** [comment]
While this did fix the issue with the sidebar on the left, now, on mobile, the right-menu still has some scrolling issues.

If I collapse my browser window small enough where the left sidebar disappears and the mobile menu icon appears, clicking on the mobile menu does not allow me to scroll through the long list of menu items.

**Comment by flynnduism** [comment]
Thanks @ultimateboy. I'm testing it and able to scroll through the full list, can you elaborate on the menu scrolling issue you're seeing -

Is the hamburger not opening? Or is it that the right-hand menu isn't scrolling through the full list?

**Comment by ultimateboy** [comment]
Attaching screen capture to what I see: 
docs-sidebar

**Comment by flynnduism** [comment]
mobile-scroll

Alright, looks like using `height: 100%` to get a nicely positioned footer was causing scrolling hi-jinx. Thanks for helping me figure it out @ultimateboy, should be all sorted.

**Comment by ultimateboy** [comment]
Seems much better to me. There's still some oddness when you increase your browser width with the menu open, but given it all works at the resolution the site is loaded, I'm going to call this good.

**Pull request merged**
