### PR TITLE
Revert "ref(scheduler): split up k8s.py and make it more modular"

### PR DESCRIPTION
**Pull request by mboersma**
This reverts commit 218bfe25cbb6c1d80324a1be7919cf82e9c2e54c. While it passed unit tests, it introduced errors into actual app workflow that were difficult to pin down. Again, we need to resurrect the functional tests, which would have caught the problems.

### CODE REVIEW

**Comment by arschles** [comment]
@mboersma gave a LGTM. worth testing locally before merge though? I can do so

**Comment by mboersma** [comment]
@arschles more testing is always helpful, but I did test this interactively on a local cluster already.

**Comment by bacongobbler** [comment]
sorry for the delays, had my head down in the sand. :shipit:!

**Comment by arschles** [comment]
@mboersma ok, this may unblock me anyway. I'll test after it's built and pushed

**Comment by krancour** [comment]
fwiw, sorry to see this undone.  I assume we'll come back to this eventually?

**Comment by mboersma** [comment]
I hope so! But first there needs to be a component-level or functional test that would have the breakage here.

**Pull request merged**
