### PR TITLE
RBAC support

### PR DESCRIPTION
**Pull request by Bregor**
One commit to rule them all:

- https://github.com/deis/builder/pull/513
- https://github.com/deis/controller/pull/1292
- https://github.com/deis/fluentd/pull/96
- https://github.com/deis/monitor/pull/195
- https://github.com/deis/router/pull/344

### CODE REVIEW

**Comment by vdice** [comment]
A note for how to install the entire Workflow chart with relevant PR sub-chart versions added:

If you haven't done so, add the necessary chart repos for all RBAC-ified components to helm:
```
$ for repo in fluentd-pr router-pr monitor-pr controller-pr builder-pr; do \
    helm repo add $repo https://charts.deis.com/$repo; \
done
```
Next, fetch the latest workflow-dev chart:
```
$ helm repo add workflow-dev https://charts.deis.com/workflow-dev # if needed
$ helm fetch --untar workflow-dev/workflow # --version ">=0.0.0-a" is also needed in helm v2.4.x
```
Substitute the following `requirements.yaml` in place of the existing `workflow/requirements.yaml`:
```
dependencies:
  - name: builder
    version: "v2.10.2-20170512171907-sha.c891804"
    repository: https://charts.deis.com/builder-pr
  - name: slugbuilder
    version: ">=v2.4.12-dev"
    repository: https://charts.deis.com/slugbuilder-dev
  - name: dockerbuilder
    version: ">=v2.7.2-dev"
    repository: https://charts.deis.com/dockerbuilder-dev
  - name: controller
    version: "v2.14.1-20170512220835-sha.c821f94"
    repository: https://charts.deis.com/controller-pr
  - name: slugrunner
    version: ">=v2.3.0-dev"
    repository: https://charts.deis.com/slugrunner-dev
  - name: database
    version: ">=v2.5.3-dev"
    repository: https://charts.deis.com/database-dev
  - name: fluentd
    version: "v2.9.1-20170512163817-sha.464bbd9"
    repository: https://charts.deis.com/fluentd-pr
  - name: redis
    version: ">=v2.2.6-dev"
    repository: https://charts.deis.com/redis-dev
  - name: logger
    version: ">=v2.4.3-dev"
    repository: https://charts.deis.com/logger-dev
  - name: minio
    version: ">=v2.3.5-dev"
    repository: https://charts.deis.com/minio-dev
  - name: monitor
    version: "v2.9.1-20170512172938-sha.ff4058d"
    repository: https://charts.deis.com/monitor-pr
  - name: nsqd
    version: ">=v2.2.7-dev"
    repository: https://charts.deis.com/nsqd-dev
  - name: registry
    version: ">=v2.4.0-dev"
    repository: https://charts.deis.com/registry-dev
  - name: registry-proxy
    version: ">=v1.3.0-dev"
    repository: https://charts.deis.com/registry-proxy-dev
  - name: registry-token-refresher
    version: ">=v1.1.2-dev"
    repository: https://charts.deis.com/registry-token-refresher-dev
  - name: router
    version: "v2.12.2-20170512173445-sha.fe18379"
    repository: https://charts.deis.com/router-pr
  - name: workflow-manager
    version: ">=v2.5.0-dev"
    repository: https://charts.deis.com/workflow-manager-dev
```
Finally, update with the specified dependencies and install the chart:
```
$ helm dependency update workflow
...
$ helm install workflow --name deis-workflow --namespace deis
```

**Comment by vdice** [comment]
Note: router chart version updated in `requirements.yaml` from above w/ latest changes pushed to https://github.com/deis/router/pull/344

**Comment by vdice** [comment]
Closes https://github.com/deis/workflow/issues/809

**Comment by vdice** [comment]
latest controller chart version added to https://github.com/deis/workflow/pull/812#issuecomment-301204826

**Comment by vdice** [comment]
Thanks so much for the contribution @Bregor ! This was a huge effort and very much appreciated.  Merging this and associated PRs and we can do a final round of testing once we have a 2.15 release candidate chart...

**Comment by Bregor** [comment]
@vdice great! Thanks for you help and patience!

**Pull request merged**
