### PR TITLE
ref(ci): rm travis and unused scripts

### PR DESCRIPTION
**Pull request by vdice**
Re: removing Travis, Jenkins handles CI around building and testing the docker image via the [workflow-docs](https://ci.deis.io/job/workflow-docs/) job.  See also the job [configuration](https://github.com/deis/jenkins-jobs/blob/master/jobs/workflow_docs.groovy)

### CODE REVIEW

**Comment by bacongobbler** [comment]
yep, `make docker-build docker-test` should cover all the steps Travis currently does. 👍

**Comment by bacongobbler** [comment]
Isn't the gutenbuild script still needed for the deis.com job though, or is the docs deployed a different way now?

**Comment by vdice** [comment]
> Isn't the gutenbuild script still needed for the deis.com job though, or is the docs deployed a different way now?

Great question; hoping to get clarity from @slack or @ultimateboy on this detail.

**Comment by ultimateboy** [comment]
That script is used by gutenberg: https://github.com/deis/gutenberg/blob/master/script/compile#L26

**Comment by vdice** [comment]
Thanks @ultimateboy -- `_scripts/gutenbuild` added back/not deleted.  Could I get your blessing before merging?

**Comment by bacongobbler** [comment]
Looks good to me.

**Pull request merged**
