### PR TITLE
feat(hooks): add fingerprint to key hooks API response

### PR DESCRIPTION
**Pull request by helgi**
/cc @aledbf

### CODE REVIEW

**Comment by smothiki** [comment]
We can generate finger print from the Pubkey . Do we have to explicitly send finger print ?

**Comment by helgi** [comment]
We can, it's extra overhead in the builder but I'd say it's pretty minimal overhead given most fingerprint operations I've worked with.

**Comment by bacongobbler** [comment]
Do we have a PR in builder that moves to this behaviour?

**Comment by helgi** [comment]
Not yet. @aledbf started a WIP one tho

**Pull request merged**
