### PR TITLE
doc(styles): theme the docs to match deis.com

### PR DESCRIPTION
**Pull request by flynnduism**
This PR updates the Documentation theme (using MK Docs) to follow the style and brand of deis.com.

docs

- [x] fix the sidebar menu states
- [x] clean up old theme JS
- [x] minify assets
- [x] browser test

_Note:_ changes to the makefile compile the .com and the docs sass files into a single `styles.css` - but doing so makes sass a requirement. Perhaps I should omit this and only commit compiled css.

### CODE REVIEW

**Comment by slack** [comment]
Couple of questions!
* v1 docs should link to docs.deis.io
* we will need to make the header links fully qualified urls.. when this is published to read the docs `/why-deis` won't work
* do we need to check in all the bower_components now that the compiled css is checked in?

Have the `deploy_website` jenkins job wired up to this branch:
* https://ci.deis.io/job/deploy_website/159/console
* http://deis-www-staging.s3-website-us-east-1.amazonaws.com/docs/workflow/

**Comment by flynnduism** [comment]
@slack Thanks!

Urls updated, removed the bower assets directory from the theme.

**Comment by slack** [comment]
Excellent! Triggered a new deploy to staging:
* https://ci.deis.io/job/deploy_website/160/console

**Comment by slack** [comment]
Looks like this needs a reeeebase

**Comment by flynnduism** [comment]
Closing in favor of #302.

**Pull request closed without merging**
