### PR TITLE
chore(django): bump to django 1.9.3

### PR DESCRIPTION
**Pull request by helgi**
https://docs.djangoproject.com/en/1.9/releases/1.9.3/

### CODE REVIEW

**Comment by bacongobbler** [comment]
hmm... looks like it wasn't released on pip at that time?

**Comment by helgi** [comment]
lol oops it's under development. Only noticed it when reviewing new 1.10 things compared to a few weeks ago and I figured I might throw it in. Oh well!

**Comment by helgi** [comment]
Django 1.9.3 has been released

**Comment by jchauncey** [comment]
built this, pushed a new deploy of example go and everything seemed to work fine.

**Comment by jchauncey** [comment]
@helgi this is ready to merge

**Pull request merged**
