### PR TITLE
Add instructions to downgrade GKE node versions

### PR DESCRIPTION
**Pull request by foxycoder**
After spending too much time on installing Workflow, @kmala pointed out in Slack that I was probably running on k8s 1.3.x. Which is the default. I checked in the Console and there is no other way than to create the new cluster then downgrade it.

Hope with this (temporary) fix in the docs, other people will not make the same mistake. 😉 

See a preview of my additions below:

## Check Kubernetes version

[](http://cd.sseu.re/2016_07_20_16_25_45_afsqg.jpg)

After the cluster is created, check the node version. If you are on 1.3.x, **downgrade the node version to 1.2.5**. See [Kubernetes Versions](https://deis.com/docs/workflow/installing-workflow/system-requirements/#kubernetes-versions) under System Requirements for more details.

### CODE REVIEW

**Comment by mboersma** [comment]
For reference, here is the bug that makes this downgrade necessary for now: https://github.com/deis/workflow/issues/372

**Comment by slack** [comment]
Thanks for the clarification @foxycoder would you mind if we mirrored the screenshot under deis.com?

**Comment by smothiki** [comment]
@mboersma we should merge this and rebase the https://github.com/deis/workflow/pull/387

**Comment by mboersma** [comment]
> we should merge this

The image URL needs to be updated though, so deis.com isn't relying on an unrelated web host. We could merge this and then quickly follow up by re-hosting the image in a different PR. Whatcha think @slack?

**Comment by foxycoder** [comment]
Hi sorry I moved the image the repo. Hope this helps. :)

**Comment by slack** [comment]
Great, thanks!

**Pull request merged**
