### PR TITLE
fix(api): update out of date cert api docs

### LINKED ISSUE #338: Cert creation API documentation is out of date
It was updated in the controller but the documentation was never updated.

### PR DESCRIPTION
**Pull request by Joshua-Anderson**
Fixes #338

### CODE REVIEW

**Comment by helgi** [comment]
Nice - It is missing the attach and detach endpoints but that's probably fine for now

**Comment by Joshua-Anderson** [comment]
@helgi I'll fix that tomorrow morning!

**Comment by helgi** [comment]
Sweet thanks!

**Comment by Joshua-Anderson** [comment]
@helgi Added attach and detach.

**Pull request merged**
