### PR TITLE
feat(healthcheck_test.go): add test for healthcheck

### PR DESCRIPTION
**Pull request by arschles**
Ref #183

### CODE REVIEW

**Comment by bacongobbler** [comment]
where's the `git push`? I see an app created in the code but no build has been created for us to scale (through `git push deis master` or a `deis pull`).

**Comment by arschles** [comment]
@bacongobbler a `deis pull` is forthcoming...

**Comment by arschles** [comment]
@bacongobbler ok, `deis pull` is added now, and this PR is ready for review.

Also note that I had to add functionality to get the router's URL, so that the new test can make requests against the app itself. I'm open to ideas on how to better accomplish the goal of making requests against the app.

**Comment by arschles** [comment]
closing, as deis/workflow-e2e#4 has replaced this and been merged

**Pull request closed without merging**
