### PR TITLE
Fixes #346 - removes labels annotion in whitelist

### LINKED ISSUE #346: Docs: old annotation for ip whitelist doesn't work in V2
Using labels in whitelist annotation not supported in deis workflow - need to update docs to reflect that.

https://github.com/deis/workflow/blob/master/src/managing-workflow/security-considerations.md#ip-whitelist

```bash
$ kubectl --namespace=deis annotate service deis-controller router.deis.io/whitelist="10.0.1.0/24:office_intranet,121.212.121.212:dev_jenkins"

And the same applies to applications. For example, to apply a whitelist to an application named example:

$ kubectl --namespace=example annotate service example-web router.deis.io/whitelist="10.0.1.0/24:office_intranet,121.212.121.212:dev_jenkins"
```

Need to remove the `:office_intranet` and `:dev_jenkins`
per @krancour the labels aren't currently supported.
Creating PR to fix now.

### PR DESCRIPTION
**Pull request by dmcnaught**
https://github.com/deis/workflow/issues/346

### CODE REVIEW

**Comment by krancour** [comment]
For more context, see [this comment](https://github.com/deis/workflow/issues/346#issuecomment-228479113).

**Comment by krancour** [comment]
@dmcnaught, thank you for fixing this.

Can I just ask you to please amend the commit message to observe our usual conventions? (It's so the changlelog-generating script will work.)

Something like this:

docs(router): Remove invalid labels from example whitelists

Pending that, LGTM2.

**Comment by dmcnaught** [comment]
@krancour Sure - like that?

**Comment by bacongobbler** [comment]
excellent.

**Pull request merged**
