### PR TITLE
fix(migrations): remove etcd migration code from boot

### PR DESCRIPTION
**Pull request by helgi**
Needed for boot script

### CODE REVIEW

**Comment by bacongobbler** [comment]
let's just remove the etcd migrations part from the boot script instead :)

**Comment by helgi** [comment]
Could do that, no chance we'd ever want to use it for something? :P k8s migrations instead?

**Comment by bacongobbler** [comment]
nah I don't think so if we're wanting to eventually move away from etcd in Deis: https://github.com/deis/etcd/issues/10

**Comment by helgi** [comment]
Ditched it

**Comment by bacongobbler** [comment]
good bye etcd migrations; you won't be missed :balloon: :balloon:

**Comment by bacongobbler** [comment]
merging as this is a showstopper and we have 2 LGTMs at this point. Thanks @helgi!

**Pull request merged**
