### PR TITLE
fix(azure): use regular storage instead of premium

### LINKED ISSUE #693: deis-database backup not working in new Azure installation causing DB to not work at all
Followed the start guide then:

- az storage account create -n $SA_NAME -l $DC_LOCATION -g $RG_NAME --sku Premium_LRS
-  helm install deis/workflow --namespace=deis --set controller.k8s_api_verify_tls=false,global.storage=azure,azure.accountname=$SA_NAME,azure.accountkey=$SA_KEY,azure.registry_container=registry,azure.database_container=database,azure.builder_container=builder

after 20mins deis-controller is restarting, checking logs says it cannot connect to deis-database, db logs say:

```
server started
Performing an initial backup...
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-push".
        STRUCTURED: time=2017-01-10T20:22:33.294209-00 pid=106
wal_e.worker.upload INFO     MSG: begin archiving a file
        DETAIL: Uploading "pg_xlog/000000010000000000000001" to "wabs://database/wal_005/000000010000000000000001.lzo".
        STRUCTURED: time=2017-01-10T20:22:34.201929-00 pid=120 action=push-wal key=wabs://database/wal_005/000000010000000000000001.lzo prefix= seg=000000010000000000000001 state=begin
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/azure/storage/storageclient.py", line 171, in _perform_request
    resp = self._filter(request)
  File "/usr/local/lib/python3.5/dist-packages/azure/storage/storageclient.py", line 160, in _perform_request_worker
    return self._httpclient.perform_request(request)
  File "/usr/local/lib/python3.5/dist-packages/azure/storage/_http/httpclient.py", line 223, in perform_request
    raise HTTPError(status, message, respheaders, respbody)
azure.storage._http.HTTPError: Block blobs are not supported.
```

### PR DESCRIPTION
**Pull request by bacongobbler**
premium storage does not support block blobs, whereas regular storage does.

Error coming from wal-e, which makes workflow completely unusable with this setup:

```
azure.storage._http.HTTPError: Block blobs are not supported.
```

cc @dtzar @slack.

closes #693.

### CODE REVIEW

**Comment by bacongobbler** [comment]
Commit that changed this behaviour would be https://github.com/deis/workflow/commit/bb54bef54ac1600d59ac1b5bc868c282cfb12b45

**Comment by dtzar** [comment]
Yes, it is true that premium storage doesn't support page blobs.  https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/using-blob-service-operations-with-azure-premium-storage

Your removal of the premium LRS switch should do the trick.

**Comment by slack** [comment]
Looks like `Standard_LRS` would work!?

https://docs.microsoft.com/en-us/rest/api/storagerp/srp_sku_types

**Comment by bacongobbler** [comment]
thanks guys! Edited the PR to just switch the --sku flag to Standard_LRS.

**Comment by dtzar** [comment]
LGTM2

**Comment by jalberto** [comment]
confirmed, it works with Standar_LRS

**Pull request merged**
