### PR TITLE
fix(tests): restrict app name length to 24 characters

### PR DESCRIPTION
**Pull request by bacongobbler**

### CODE REVIEW

**Comment by arschles** [comment]
@bacongobbler FYI the same functionality was done by @lanej in https://github.com/deis/workflow/pull/189/files#diff-c970541257d7d853bf0c55878ff9b32cR31. I'm partial to the way you've done it here. @lanej do you mind removing that change from your PR?

**Comment by arschles** [comment]
@bacongobbler @lanej are both of you ok with merging this?

**Comment by lanej** [comment]
sure. im getting good at rebasing

**Comment by bacongobbler** [comment]
looks like https://github.com/deis/workflow/commit/7c3fbe6d6c96886ee1d2fb6726471a873ab8a539 fixed this behaviour up so this is no longer necessary :)

**Comment by arschles** [comment]
ah @bacongobbler I forgot about that. thanks

**Pull request closed without merging**
