### PR TITLE
fix(scheduler) scheduler stops a scale operation early if desired is the same as current number of pods

### LINKED ISSUE #505: 503 in ps:scale scenario
The e2e test seen [here](https://github.com/deis/workflow-e2e/blob/master/tests/builds_test.go#L99) intermittently encounters a `503 Service Unavailable` as a result of a `deis ps:scale` command:

```
$ deis builds:create deis/example-go:latest -a test-944111811
Creating build... done
$ deis ps:list --app=test-944111811
=== test-944111811 Processes
--- cmd:
test-944111811-v3-cmd-3jvn8 up (v3)
Waiting up to 10 seconds for `curl -sL -w "%{http_code}\\n" "http://test-944111811.130.211.157.213.xip.io" -o /dev/null` to return 200...
$ curl -sL -w "%{http_code}\\n" "http://test-944111811.130.211.157.213.xip.io" -o /dev/null
200
$ deis pull deis/example-go:latest -a test-944111811 --procfile="worker: while true; do echo hi; sleep 3; done"
Creating build... done
$ deis ps:scale worker=1 -a test-944111811
Scaling processes... but first, coffee!
Error:
503 Service Unavailable
detail: test-944111811-v4-worker (Scale): failed to scale ReplicationController "test-944111811-v4-worker": 409 Conflict
{'kind': 'Status', 'code': 409, 'apiVersion': 'v1', 'reason': 'Conflict', 'message': 'replicationControllers "test-944111811-v4-worker" cannot be updated: the object has been modified; please apply your changes to the latest version and try again', 'details': {'kind': 'replicationControllers', 'name': 'test-944111811-v4-worker'}, 'metadata': {}, 'status': 'Failure'}

$ deis apps:destroy --app=test-944111811 --confirm=test-944111811
Destroying test-944111811...
done in 0s
$ rm -rf .git

• Failure [87.204 seconds]
Builds
/go/src/github.com/deis/workflow-e2e/tests/builds_test.go:138
  with a logged-in user
  /go/src/github.com/deis/workflow-e2e/tests/builds_test.go:137
    with a deployed app
    /go/src/github.com/deis/workflow-e2e/tests/builds_test.go:136
      can create a build from an existing image ("deis pull") [It]
      /go/src/github.com/deis/workflow-e2e/tests/builds_test.go:135

      No future change is possible.  Bailing out early after 9.766s.
      Got stuck at:
           coffee!
          ...
      Waiting for:
          done in \d+s

      /go/src/github.com/deis/workflow-e2e/tests/builds_test.go:117
------------------------------
```

The controller pod logs show (`healthz` checks removed):
```
...
10.196.2.1 "POST /v2/keys/ HTTP/1.1" 201 964 "Deis Client v2.0.0-dev"
10.196.2.1 "GET /v2/ HTTP/1.1" 401 58 "Deis Client v2.0.0-dev"
10.196.2.1 "POST /v2/auth/login/ HTTP/1.1" 200 52 "Deis Client v2.0.0-dev"
INFO test-113928669: config test-113928669-6d926d3 updated
INFO test-113928669: release test-113928669-v1 created
INFO [test-113928669]: test-81 created initial release
DEBUG create test-113928669
INFO test-113928669: domain test-113928669 added
INFO [test-113928669]: domain test-113928669 added
10.196.2.1 "POST /v2/apps/ HTTP/1.1" 201 172 "Deis Client v2.0.0-dev"
INFO test-944111811: config test-944111811-7612dd8 updated
INFO test-944111811: release test-944111811-v1 created
INFO [test-944111811]: test-81 created initial release
DEBUG create test-944111811
INFO test-944111811: domain test-944111811 added
INFO [test-944111811]: domain test-944111811 added
10.196.2.1 "POST /v2/apps/ HTTP/1.1" 201 172 "Deis Client v2.0.0-dev"
10.196.2.1 "GET /v2/hooks/key/60:6c:ff:62:bd:31:71:3b:0d:04:06:a3:56:70:24:10 HTTP/1.1" 200 71 "deis-builder"
10.196.2.1 "POST /v2/hooks/push HTTP/1.1" 201 398 "deis-builder"
10.196.2.1 "POST /v2/hooks/config HTTP/1.1" 200 201 "deis-builder"
INFO test-944111811: build test-944111811-3529c40 created
INFO test-944111811: release test-944111811-v2 created
INFO [test-944111811]: test-81 deployed 779ca3d
DEBUG create test-944111811
DEBUG deploy test-944111811-v2-web, img http://10.199.243.217:9000/git/home/test-944111811:git-779ca3d7/push/slug.tgz, params {'app_type': 'web', 'cpu': {}, 'memory': {}, 'healthcheck': {}, 'envs': {}, 'version': 'v2', 'build_type': 'buildpack', 'num': 0, 'tags': {}}, cmd "start web"
DEBUG Failed to find port for Docker image 10.199.248.199:80/http://10.199.243.217:9000/git/home/test-944111811:git-779ca3d7/push/slug.tgz, defaulting to 5000
DEBUG scaling release test-944111811-v2-web to 1 out of final 1
DEBUG scaling RC test-944111811-v2-web in namespace test-944111811 from 0 to 1 replicas
DEBUG waiting for RC test-944111811-v2-web to get a newer resource version than 34534 (30s timeout)
DEBUG RC test-944111811-v2-web has a new resource version 34535
DEBUG waiting for 1 pods in test-944111811 namespace to be in services (120s timeout)
DEBUG 1 out of 1 pods in namespace test-944111811 are in service
DEBUG scaled up pod number 1 for test-944111811-v2-web
10.196.2.1 "POST /v2/hooks/build HTTP/1.1" 200 25 "deis-builder"
INFO test-944111811: build test-944111811-e52b276 created
INFO test-944111811: release test-944111811-v3 created
INFO [test-944111811]: test-81 deployed deis/example-go:latest
INFO Pulling Docker image deis/example-go:latest
INFO Tagging Docker image deis/example-go:latest as 10.199.248.199:80/test-944111811:v3
INFO Pushing Docker image 10.199.248.199:80/test-944111811:v3
DEBUG create test-944111811
DEBUG deploy test-944111811-v3-cmd, img test-944111811:v3, params {'app_type': 'cmd', 'cpu': {}, 'memory': {}, 'healthcheck': {}, 'envs': {}, 'version': 'v3', 'build_type': 'deispull', 'num': 0, 'tags': {}}, cmd ""
DEBUG scaling release test-944111811-v3-cmd to 1 out of final 1
DEBUG scaling RC test-944111811-v3-cmd in namespace test-944111811 from 0 to 1 replicas
DEBUG waiting for RC test-944111811-v3-cmd to get a newer resource version than 34552 (30s timeout)
DEBUG RC test-944111811-v3-cmd has a new resource version 34553
DEBUG waiting for 1 pods in test-944111811 namespace to be in services (120s timeout)
DEBUG 1 out of 1 pods in namespace test-944111811 are in service
DEBUG scaled up pod number 1 for test-944111811-v3-cmd
10.196.2.1 "POST /v2/apps/test-944111811/builds/ HTTP/1.1" 201 248 "Deis Client v2.0.0-dev"
10.196.2.1 "GET /v2/apps/test-944111811/pods/?limit=1000 HTTP/1.1" 200 136 "Deis Client v2.0.0-dev"
INFO test-944111811: build test-944111811-66fd3f5 created
INFO test-944111811: release test-944111811-v4 created
INFO [test-944111811]: test-81 deployed deis/example-go:latest
INFO Pulling Docker image deis/example-go:latest
INFO Tagging Docker image deis/example-go:latest as 10.199.248.199:80/test-944111811:v4
INFO Pushing Docker image 10.199.248.199:80/test-944111811:v4
DEBUG create test-944111811
DEBUG deploy test-944111811-v4-cmd, img test-944111811:v4, params {'app_type': 'cmd', 'cpu': {}, 'memory': {}, 'healthcheck': {}, 'envs': {}, 'version': 'v4', 'build_type': 'deispull', 'num': 0, 'tags': {}}, cmd ""
DEBUG scaling release test-944111811-v4-cmd to 1 out of final 1
DEBUG scaling RC test-944111811-v4-cmd in namespace test-944111811 from 0 to 1 replicas
DEBUG waiting for RC test-944111811-v4-cmd to get a newer resource version than 34567 (30s timeout)
DEBUG RC test-944111811-v4-cmd has a new resource version 34568
DEBUG waiting for 1 pods in test-944111811 namespace to be in services (120s timeout)
DEBUG 1 out of 1 pods in namespace test-944111811 are in service
DEBUG scaled up pod number 1 for test-944111811-v4-cmd
DEBUG scaling old release test-944111811-v3-cmd from original 1 to 0
DEBUG scaling RC test-944111811-v3-cmd in namespace test-944111811 from 1 to 0 replicas
DEBUG waiting for RC test-944111811-v3-cmd to get a newer resource version than 34557 (30s timeout)
DEBUG RC test-944111811-v3-cmd has a new resource version 34582
DEBUG waiting for 1 pods in test-944111811 namespace to be terminated (120s timeout)
DEBUG 1 pods in namespace test-944111811 are terminated
DEBUG scaled down pod number 1 for test-944111811-v3-cmd
10.196.2.1 "POST /v2/apps/test-944111811/builds/ HTTP/1.1" 201 278 "Deis Client v2.0.0-dev"
DEBUG create test-944111811
INFO test-944111811: test-81 scaled containers worker=1
INFO [test-944111811]: test-81 scaled containers worker=1
DEBUG scale test-944111811-v4-worker, img test-944111811:v4, params {'app_type': 'worker', 'cpu': {}, 'memory': {}, 'healthcheck': {}, 'envs': {}, 'version': 'v4', 'build_type': 'deispull', 'num': 1, 'tags': {}}, cmd "bash -c 'while true; do echo hi; sleep 3; done'"
DEBUG scaling RC test-944111811-v4-worker in namespace test-944111811 from 1 to 1 replicas
DEBUG Scaling failed because of: failed to scale ReplicationController "test-944111811-v4-worker": 409 Conflict
{'kind': 'Status', 'code': 409, 'apiVersion': 'v1', 'reason': 'Conflict', 'message': 'replicationControllers "test-944111811-v4-worker" cannot be updated: the object has been modified; please apply your changes to the latest version and try again', 'details': {'kind': 'replicationControllers', 'name': 'test-944111811-v4-worker'}, 'metadata': {}, 'status': 'Failure'}
DEBUG scaling RC test-944111811-v4-worker in namespace test-944111811 from 1 to 1 replicas
DEBUG waiting for RC test-944111811-v4-worker to get a newer resource version than 34600 (30s timeout)
DEBUG RC test-944111811-v4-worker has a new resource version 34602
DEBUG waiting for 1 pods in test-944111811 namespace to be in services (120s timeout)
DEBUG 1 out of 1 pods in namespace test-944111811 are in service
ERROR test-944111811: test-944111811-v4-worker (scale): test-944111811-v4-worker (Scale): failed to scale ReplicationController "test-944111811-v4-worker": 409 Conflict
{'kind': 'Status', 'code': 409, 'apiVersion': 'v1', 'reason': 'Conflict', 'message': 'replicationControllers "test-944111811-v4-worker" cannot be updated: the object has been modified; please apply your changes to the latest version and try again', 'details': {'kind': 'replicationControllers', 'name': 'test-944111811-v4-worker'}, 'metadata': {}, 'status': 'Failure'}
ERROR [test-944111811]: test-944111811-v4-worker (scale): test-944111811-v4-worker (Scale): failed to scale ReplicationController "test-944111811-v4-worker": 409 Conflict
{'kind': 'Status', 'code': 409, 'apiVersion': 'v1', 'reason': 'Conflict', 'message': 'replicationControllers "test-944111811-v4-worker" cannot be updated: the object has been modified; please apply your changes to the latest version and try again', 'details': {'kind': 'replicationControllers', 'name': 'test-944111811-v4-worker'}, 'metadata': {}, 'status': 'Failure'}
10.196.2.1 "POST /v2/apps/test-944111811/scale/ HTTP/1.1" 503 499 "Deis Client v2.0.0-dev"
DEBUG destroy test-944111811
WARNING test-944111811: Error deleting existing application logs: HTTPConnectionPool(host='127.0.0.1', port=80): Max retries exceeded with url: /logs/test-944111811 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f46ba6cdb00>: Failed to establish a new connection: [Errno 111] Connection refused',))
WARNING [test-944111811]: Error deleting existing application logs: HTTPConnectionPool(host='127.0.0.1', port=80): Max retries exceeded with url: /logs/test-944111811 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f46ba6cdb00>: Failed to establish a new connection: [Errno 111] Connection refused',))
INFO test-944111811: domain test-944111811 removed
INFO [test-944111811]: domain test-944111811 removed
10.196.2.1 "DELETE /v2/apps/test-944111811/ HTTP/1.1" 204 - "Deis Client v2.0.0-dev"
10.196.2.1 "GET /v2/ HTTP/1.1" 401 58 "Deis Client v2.0.0-dev"
10.196.2.1 "POST /v2/auth/login/ HTTP/1.1" 200 52 "Deis Client v2.0.0-dev"
10.196.2.1 "GET /v2/apps/?limit=100 HTTP/1.1" 200 224 "Deis Client v2.0.0-dev"
DEBUG destroy test-113928669
WARNING test-113928669: Error deleting existing application logs: HTTPConnectionPool(host='127.0.0.1', port=80): Max retries exceeded with url: /logs/test-113928669 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f46ba59bf60>: Failed to establish a new connection: [Errno 111] Connection refused',))
WARNING [test-113928669]: Error deleting existing application logs: HTTPConnectionPool(host='127.0.0.1', port=80): Max retries exceeded with url: /logs/test-113928669 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f46ba59bf60>: Failed to establish a new connection: [Errno 111] Connection refused',))
INFO test-113928669: domain test-113928669 removed
INFO [test-113928669]: domain test-113928669 removed
10.196.2.1 "DELETE /v2/apps/test-113928669/ HTTP/1.1" 204 - "Deis Client v2.0.0-dev"
10.196.2.1 "GET /v2/ HTTP/1.1" 401 58 "Deis Client v2.0.0-dev"
10.196.2.1 "POST /v2/auth/login/ HTTP/1.1" 200 52 "Deis Client v2.0.0-dev"
10.196.2.1 "DELETE /v2/auth/cancel/ HTTP/1.1" 204 - "Deis Client v2.0.0-dev"
10.196.2.1 "GET /v2/ HTTP/1.1" 401 58 "Deis Client v2.0.0-dev"
10.196.2.1 "POST /v2/auth/login/ HTTP/1.1" 200 52 "Deis Client v2.0.0-dev"
10.196.2.1 "GET /v2/apps/?limit=100 HTTP/1.1" 200 221 "Deis Client v2.0.0-dev"
10.196.2.1 "GET /v2/ HTTP/1.1" 401 58 "Deis Client v2.0.0-dev"
10.196.2.1 "POST /v2/auth/login/ HTTP/1.1" 200 52 "Deis Client v2.0.0-dev"
10.196.2.1 "DELETE /v2/auth/cancel/ HTTP/1.1" 204 - "Deis Client v2.0.0-dev"
...
```

### PR DESCRIPTION
**Pull request by helgi**
Fixes #505

### CODE REVIEW

**Comment by bacongobbler** [comment]
this should also fix up https://github.com/deis/workflow/issues/483, I'd imagine.

**Comment by helgi** [comment]
No that is an unrelated ticket, but I closed it anyway

**Comment by arschles** [comment]
@helgi any unit test you can add/modify here?

**Comment by helgi** [comment]
No, the current master mock scheduler doesn't even reach into the `scale` code

**Comment by arschles** [comment]
k

**Pull request merged**
